version: '3.8'

services:
  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: twinup-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - twinup-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # ClickHouse Database  
  clickhouse:
    image: clickhouse/clickhouse-server:23.8-alpine
    container_name: twinup-clickhouse
    ports:
      - "9000:9000"
      - "8123:8123"
    environment:
      CLICKHOUSE_DB: sensor_data
      CLICKHOUSE_USER: twinup
      CLICKHOUSE_PASSWORD: twinup123
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/init:/docker-entrypoint-initdb.d
    networks:
      - twinup-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redis_data:
  clickhouse_data:

networks:
  twinup-network:
    driver: bridge
