# TWINUP Sensor Consumer Service Configuration
# Yüksek performanslı veri işleme için optimize edilmiş ayarlar

kafka:
  brokers:
    - "localhost:9092"
  topic: "sensor-data"
  group_id: "sensor-consumer-group"
  auto_commit: false              # Manual commit for better control
  commit_interval: "1s"           # Commit every second
  session_timeout: "30s"          # Consumer session timeout
  heartbeat_interval: "3s"        # Heartbeat interval
  fetch_min: 1                    # Minimum bytes to fetch
  fetch_default: 1048576          # Default fetch size (1MB)
  fetch_max: 10485760             # Maximum fetch size (10MB)
  retry_backoff: "2s"             # Retry backoff time

clickhouse:
  host: "localhost"
  port: 9000
  database: "sensor_data"
  username: "twinup"
  password: "twinup123"
  max_open_conns: 10              # Maximum open connections
  max_idle_conns: 5               # Maximum idle connections
  conn_max_lifetime: "1h"         # Connection max lifetime
  batch_size: 1000                # Batch insert size
  batch_timeout: "5s"             # Force flush after timeout
  async_insert: true              # Enable async inserts for performance

redis:
  host: "localhost"
  port: 6379
  password: ""                    # No password for development
  database: 0                     # Default database
  pool_size: 20                   # Connection pool size
  min_idle_conns: 5               # Minimum idle connections
  max_retries: 3                  # Maximum retry attempts
  dial_timeout: "5s"              # Connection timeout
  read_timeout: "3s"              # Read timeout
  write_timeout: "3s"             # Write timeout
  idle_timeout: "5m"              # Idle connection timeout
  ttl: "5m"                       # Cache TTL (Time To Live)
  pipeline_size: 100              # Pipeline batch size

grpc:
  alert_service_addr: "localhost:50051"
  conn_timeout: "10s"             # Connection timeout
  request_timeout: "5s"           # Request timeout
  max_retries: 3                  # Maximum retry attempts
  retry_backoff: "1s"             # Retry backoff time
  keep_alive: "30s"               # Keep alive time
  keep_alive_timeout: "5s"        # Keep alive timeout

consumer:
  worker_count: 5                 # Number of processing workers
  buffer_size: 5000               # Internal buffer size
  processing_timeout: "30s"       # Processing timeout
  enable_benchmark: true          # Enable performance logging
  benchmark_interval: "10s"       # Log stats every 10 seconds
  graceful_timeout: "30s"         # Graceful shutdown timeout
  alert_threshold: 90.0           # Temperature alert threshold (°C)

metrics:
  enabled: true
  port: 8080
  path: "/metrics"

logger:
  level: "info"                   # debug, info, warn, error
  format: "json"                  # json, console
  development: false              # Enable development mode for local testing
