# TWINUP Real-Time Analytics Service Configuration
# Gerçek zamanlı analiz ve MQTT publishing için optimize edilmiş ayarlar

kafka:
  brokers:
    - "localhost:9092"
  topic: "sensor-data"
  group_id: "analytics-consumer-group"
  auto_commit: true               # Auto commit for analytics (less critical than storage)
  commit_interval: "1s"           # Commit every second
  session_timeout: "30s"          # Consumer session timeout
  heartbeat_interval: "3s"        # Heartbeat interval
  fetch_min: 1                    # Minimum bytes to fetch
  fetch_default: 1048576          # Default fetch size (1MB)
  fetch_max: 10485760             # Maximum fetch size (10MB)
  retry_backoff: "2s"             # Retry backoff time

mqtt:
  broker: "tcp://localhost:1883"
  client_id: "twinup-analytics"
  username: ""                    # No auth for development
  password: ""
  qos: 1                          # QoS 1 for reliable delivery
  retained: false                 # Don't retain analytics messages
  connect_timeout: "30s"          # Connection timeout
  write_timeout: "30s"            # Write timeout
  keep_alive: "60s"               # Keep alive interval
  ping_timeout: "10s"             # Ping timeout
  connect_retry_interval: "10s"   # Retry interval
  auto_reconnect: true            # Enable auto reconnect
  max_reconnect_interval: "10m"   # Max reconnect interval
  topic_prefix: "analytics"       # Topic prefix for all analytics

analytics:
  worker_count: 3                 # Number of analytics workers
  buffer_size: 1000               # Internal buffer size
  window_size: "5m"               # Data window size for analysis
  trend_window: "15m"             # Trend analysis window
  delta_threshold: 2.0            # Significant delta threshold
  regional_analysis: true         # Enable regional analysis
  anomaly_detection: true         # Enable anomaly detection
  publish_interval: "30s"         # Periodic analytics interval
  enable_benchmark: true          # Enable performance logging
  benchmark_interval: "10s"       # Log stats every 10 seconds
  graceful_timeout: "30s"         # Graceful shutdown timeout
  max_memory_window: 10000        # Max data points in memory

metrics:
  enabled: true
  port: 8080
  path: "/metrics"

logger:
  level: "info"                   # debug, info, warn, error
  format: "json"                  # json, console
  development: false              # Enable development mode for local testing
